name = "openjij-web"
type = 'webpack'
usage_model = 'unbound'
workers_dev = true
target_type = "webpack"
compatibility_date = "2022-03-16"
account_id = 'ACCOUNT_ID'
[site]
bucket = "./public"
entry-point = "workers-site"