name = "openjij-web"
type = "javascript"
usage_model = 'unbound'
workers_dev = true
compatibility_date = "2022-03-16"
account_id = 'ACCOUNT_ID'
minify = true
main = "./worker/script.js"
[build]
command = "npm run build"
[site]
bucket = "./public"
entry-point = "workers-site"
