# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title:     OpenJij Book
author:    Jij Inc.
copyright: "2022"
logo:      OpenJij-Logo.webp
description: 'OpenJij : Framework for the Ising model and QUBO.'
only_build_toc_files: True

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
  run_in_temp:       True
  allow_errors:      False
#  stderr_output: remove
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - amsmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
  myst_url_schemes: [ mailto, http, https ] # URI schemes that will be recognised as external URLs in Markdown links
  myst_heading_anchors: -1
  myst_dmath_allow_labels: True
  myst_dmath_allow_space: True
  myst_dmath_allow_digits: True
  myst_dmath_double_inline: True
  myst_linkify_fuzzy_links: True
  myst_update_mathjax: True
  
# Information about where the book exists on the web
repository:
  url:          https://github.com/OpenJij/OpenJij  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch:       main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon:                favicon.ico
  use_issues_button:      False
  use_repository_button:  True
  use_multitoc_numbering: False
  home_page_in_navbar:    False
  use_fullscreen_button:  False
  math_renderer:          katex
  baseurl:                https://openjij.github.io/OpenJij

# Launch button settings
launch_buttons:
  notebook_interface: classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url:      https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  

sphinx:
  recursive_update: True
  config:
    numfig:                            False
    math_number_all:                   False
    math_numfig:                       False
    show_authors:                      False
    add_module_names:                  True
    gettext_allow_fuzzy_translations:  True
    gettext_uuid:                      True
    html_split_index:                  True
    python_use_unqualified_type_names: True
    nb_merge_streams:                  True
    execution_show_tb:                 True
    html_math_renderer:                katex
    katex_css_path:                    https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/katex.css
    katex_js_path:                     https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/katex.js
    katex_autorender_path:             https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/contrib/auto-render.js
    katex_prerender:                   True
    katex_inline: |
      [
        '$', '$',
        r'$', r'$',
        r'\(', r'\)', 
      ]
    katex_display: |                    
      [
        '$$', '$$',
        r'$$', r'$$',
        r'\[', r'\]', 
      ]
    katex_options: |
      displayMode: True
      output: htmlAndMathml
      leqno: True
      fleqn: True
      maxSize: Infinity
      maxExpand: Infinity 
      trust: True
      strict: False
      globalGroup: False
      macros: {"\\i": "\\mathrm{i}", "\\e": "\\mathrm{e}^{#1}", "\\vec": "\\mathbf{#1}", "\\x": "\\vec{x}", "\\d": "\\operatorname{d}\\!{}", "\\dirac": "\\operatorname{\\delta}\\left(#1\\right)", "\\scalarprod": "\\left\\langle#1,#2\\right\\rangle",  "\\eqref": "\\href{###1}{(\\text{#1})}", "\\ref": "\\href{###1}{\\text{#1}}", "\\label": "\\htmlId{#1}{}" }
    autosummary_generate:              False
    autosummary_generate_overwrite:    True
    autosummary_imported_members:      True
    autosummary_ignore_module_all:     True
    autoclass_content:                 both
    autodoc_class_signature:           separated
    autodoc_member_order:              groupwise
    autodoc_docstring_signature:       True
    autodoc_typehints:                 both
    autodoc_typehints_format:          short
    napoleon_google_docstring:         True
    napoleon_include_init_with_doc:    True
    napoleon_preprocess_types:         True
    autosectionlabel_prefix_document:  True
    autoapi_root:                      reference
    autoapi_keep_files:                False
    autoapi_dirs:                      [ ../openjij ]
    autoapi_ignore:                    [ ../openjij/_version.py, '*/_version.py' ]
    autoapi_add_toctree_entry:         False
    autoapi_python_class_content:      both
    autoapi_member_order:              groupwise
    autoapi_options: [
      members,
      inherited-members,
      undoc-members,
      show-inheritance,
      show-module-summary,
      show-inheritance-diagram,
      imported-members,
    ]
    viewcode_follow_imported_members:  True
    intersphinx_mapping:
      python:
        - "https://docs.python.org/3"
        - null
      typing-extensions:
        - "https://typing.readthedocs.io/en/latest/"
        - null
      scipy:
        - "https://docs.scipy.org/doc/scipy/reference/"
        - null
      requests:
        - "https://requests.readthedocs.io/en/latest/"
        - null
      numpy:
        - "https://numpy.org/doc/stable/" 
        - null 
      cimod:
        - "https://openjij.github.io/cimod/" 
        - null 
      pandas:
        - "https://pandas.pydata.org/pandas-docs/stable/" 
        - null
      oceandocs:
        - "https://docs.ocean.dwavesys.com/en/stable/" 
        - null
      ebp:
        - "https://executablebooks.org/en/latest/"
        - null
      myst-parser:
        - "https://myst-parser.readthedocs.io/en/latest/"
        - null
      myst-nb:
        - "https://myst-nb.readthedocs.io/en/latest/"
        - null
      sphinx:
        - "https://www.sphinx-doc.org/en/master"
        - null
      nbformat:
        - "https://nbformat.readthedocs.io/en/latest"
        - null
      sd:
        - "https://sphinx-design.readthedocs.io/en/latest"
        - null
  extra_extensions:
    - sphinx_proof
    - sphinx_inline_tabs
    - sphinx_sitemap
    - 'autoapi.extension'
    - 'sphinxcontrib.katex'
    - 'sphinx.ext.duration'
    - 'sphinx.ext.coverage'
    - 'sphinx.ext.extlinks'
    - 'sphinx.ext.githubpages'
    - 'sphinx.ext.graphviz'
    - 'sphinx.ext.doctest'
    - 'sphinx.ext.autodoc'
    - 'sphinx.ext.napoleon'
    - 'sphinx.ext.intersphinx'
    - 'sphinx.ext.viewcode'
    - 'sphinx.ext.autosummary'
    - 'sphinx.ext.autosectionlabel'
    - 'sphinx.ext.inheritance_diagram'
