name: build-test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version : ${{ matrix.python-version }}
    - name: Set up Python ${{ matrix.python-version }} cache 
      run: which python > ~/.python3_path.txt
    - uses: actions/cache@v2
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('~/.python3_path.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-
    - name: Install dependencies 
      run: |
        pip install cmake
    - name: Test 
      run: |
        python setup.py build --debug test

