name: 'Dependency Review'
on: [pull_request]

concurrency:
  group: DEPENDENCY-REVIEW-${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
