name: pypi-upload

on:
  release:
    types: [created]

jobs:
  manylinux-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build wheels
      uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2014_x86_64
      with:
        python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39'
        build-requirements: 'cmake'
        pip-wheel-args: '-w ./dist --no-deps'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version : 3.9
    - name: Upload wheels
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload dist/*manylinux*

  windows-pypi:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version : ${{ matrix.python-version }}
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install cmake wheel
        python setup.py bdist_wheel
    - name: Upload wheels
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload dist/*

  macos-pypi:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version : ${{ matrix.python-version }}
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install cmake wheel
        python setup.py bdist_wheel
    - name: Upload wheels
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload dist/*

  source-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version : 3.9
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install cmake wheel
        python setup.py sdist
    - name: Upload source
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        pip install twine
        twine upload dist/*

