name: Test Build

on:
  workflow_dispatch:
  

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.7'
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Install dependencies
      run: |
        uv pip install --system --upgrade pip setuptools wheel build cmake
    - name: pip install
      run: uv pip install --system --no-binary=openjij openjij 
